---
name: radionets
channels:
    - fastai
    - pytorch
    - defaults
dependencies:
  - python>=3.6
  - pytorch>=1.6
  - torchvision
  - cudatoolkit
  - cartopy
  - natsort
  - pip
  - pip:
    - -e .
