# This is a TOML document.

title = "Evaluation configuration"

[mode]
quiet = true

[paths]
data_path = "./example_data/"
model_path = "./build/example_model/example.model"
model_path_2 = "none"

[general]
fourier = true
amp_phase = true
source_list = false
arch_name = "filter_deep"
arch_name_2 = "none"
output_format = "png"
diff = false

[inspection]
visualize_prediction = true
visualize_source_reconstruction = true
visualize_contour = true
visualize_dynamic_range = false
visualize_ms_ssim = false
random = false
num_images = 5

[eval]
batch_size = 100
save_vals = false
save_path = "./build/"
evaluate_viewing_angle = true
evaluate_dynamic_range = true
evaluate_ms_ssim = true
evaluate_mean_diff = true
evaluate_area = true
evaluate_point = false
predict_grad = false
evaluate_gan = false
